### ISSUE TITLE
Portfolio: application deploy

### ISSUE THREAD

**Issue by JuanLPalacios** [JuanLPalacios/JuanLPalacios.github.io#7]
since the deployment was already made and added to the [README.md](https://github.com/JuanLPalacios/JuanLPalacios.github.io/blob/main/README.md) I created this issue to be able to submit it for review.

**Comment by elmar8287** [comment]
Hi @JuanLPalacios , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉🎉🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
